### ISSUE TITLE
Add copyright placeholder to license

### ISSUE THREAD

**Issue by nilsnh** [EthicalSource/hippocratic-license-3#36]
Copying in my comment from Slack: 
> I just ran into this question when looking at the [HL 3.0 license text](https://firstdonoharm.dev/version/3/0/license/license.md), should there be a placeholder for the software name and copyright holder(s) like there is on the [HL 2.1](https://firstdonoharm.dev/version/2/1/license/license.md)? I don’t know what’s strictly required of a license, I’m just used to have the software and copyright holder named in the license. (edited)

There some arguments against this practice such as:
- https://writing.kemitchell.com/2020/10/21/Copyright-Notices.html
- https://writing.kemitchell.com/2018/10/07/Copyright-Notice.html

Nevertheless, I think we landed on including a copyright placeholder after all because I believe it is a worthwhile clarification such as in cases of re-licensing. I'm very much open to discuss this.

**Comment by nilsnh** [comment]
After discussing this issue we landed on archiving it for now because it's not strictly necessary to include such a copyright notice in the license. If users request this feature in the future we can revisit this discussion.

**Comment by amalbenny** [comment]
Many of the open source developers are gaining inspiration for doing more from the attributes. Maybe we can request to mention the influence of derivative work, that's a long shot. But, ...

You can add it as a module if the initial person who use this license needs it.
