### ISSUE TITLE
typo: "or a or a"

### ISSUE THREAD

**Issue by rzmk** [EthicalSource/hippocratic-license-3#77]
I saw a typo on the builder so I did a query on the repo and these are the locations I found with it:

![image](https://github.com/EthicalSource/hippocratic-license-3/assets/30333942/e7336dc9-363c-4968-aeee-b4ce1d38f76b)

- https://github.com/EthicalSource/hippocratic-license-3/blob/fd2b5e30563b9cf66694acb7ad0141397b2898cd/content/_build-dependency-hl-3.0/modules/media.md?plain=1#L10
- https://github.com/EthicalSource/hippocratic-license-3/blob/fd2b5e30563b9cf66694acb7ad0141397b2898cd/LICENSE.md?plain=1#L123
- https://github.com/EthicalSource/hippocratic-license-3/blob/fd2b5e30563b9cf66694acb7ad0141397b2898cd/content/_build-dependency-hl-3.0/modules/law-enforcement.md?plain=1#L10

**Comment by CoralineAda** [comment]
Thanks for catching this! Fixed now. :)
